package com.epam.jwd_critics.dao;

import com.epam.jwd_critics.entity.BaseEntity;
import com.epam.jwd_critics.exception.ConnectionException;
import com.epam.jwd_critics.pool.ConnectionPool;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public abstract class AbstractBaseDao<K, T extends BaseEntity> implements BaseDao<K, T> {
    private Connection connection;

    private static final Logger logger = LoggerFactory.getLogger(AbstractBaseDao.class);

    public void setConnection(Connection connection) {
        if (this.connection == null){
            this.connection = connection;
        }
    }

    public PreparedStatement getPreparedStatement(String sql) {
        PreparedStatement ps = null;
        try {
            ps = connection.prepareStatement(sql);
        } catch (SQLException e) {
            logger.error(e.getMessage(), e);
        }
        return ps;
    }

    public PreparedStatement getPreparedStatement(String sql, int autoGeneratedKeys) {
        PreparedStatement ps = null;
        try {
            ps = connection.prepareStatement(sql, autoGeneratedKeys);
        } catch (SQLException e) {
            logger.error(e.getMessage(), e);
        }
        return ps;
    }
}
