package com.epam.jwd_critics.dao;

import com.epam.jwd_critics.entity.BaseEntity;
import com.epam.jwd_critics.exception.ConnectionException;
import com.epam.jwd_critics.pool.ConnectionPool;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public abstract class AbstractBaseDao<K, T extends BaseEntity>{
    private Connection connection;
    private final ConnectionPool connectionPool;

    private static final Logger logger = LoggerFactory.getLogger(AbstractBaseDao.class);

    public AbstractBaseDao() {
        connectionPool = ConnectionPool.getInstance();
        connection = connectionPool.getConnection();
    }

    public void returnConnectionInPool() {
        try {
            connectionPool.returnConnection(connection);
        } catch (ConnectionException e) {
            logger.error(e.getMessage(), e);
        }
    }

    public PreparedStatement getPreparedStatement(String sql) {
        PreparedStatement ps = null;
        try {
            ps = connection.prepareStatement(sql);
        } catch (SQLException e) {
            logger.error(e.getMessage(), e);
        }
        return ps;
    }

    public PreparedStatement getPreparedStatement(String sql, int autoGeneratedKeys) {
        PreparedStatement ps = null;
        try {
            ps = connection.prepareStatement(sql, autoGeneratedKeys);
        } catch (SQLException e) {
            logger.error(e.getMessage(), e);
        }
        return ps;
    }
}
